version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinical-engagement:${BUILD_TAG:-latest}
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
